import { CollectibleCard, MicroTask } from "./types";

export const INITIAL_CARDS: CollectibleCard[] = [
  {
    id: "card_air_master",
    title: "空氣吸食大師",
    description: "恭喜！因為把錢花光，你成功解鎖了『只吸空氣就能活』的宇宙最高境界。今日配額：極地冰山微風。",
    imagePrompt: "minimalist zen circle with text air floating, glowing high contrast neon turquoise",
    bgColor: "bg-emerald-950/40 border-emerald-500",
    textColor: "text-emerald-400",
    rarity: "SSR",
  },
  {
    id: "card_boba_king",
    title: "手搖飲大體積血栓",
    description: "血管裡流的不是血液，是珍奶、椰果與大把的大班新台幣。醫生看著你的超音波陷入沉思。",
    imagePrompt: "a plastic cup of boba milk tea with skeleton bones instead of pearls, hyper-stylized digital art",
    bgColor: "bg-amber-950/40 border-amber-500",
    textColor: "text-amber-400",
    rarity: "SR",
  },
  {
    id: "card_month_emperor",
    title: "月初狂暴皇帝",
    description: "發薪水當天點和牛套餐不看價錢，還叫服務生把冷氣調弱，派頭堪比杜拜法老。只威風 24 小時。",
    imagePrompt: "a golden cartoon crown on top of an empty wallet, high contrast glowing yellow",
    bgColor: "bg-yellow-950/40 border-yellow-500",
    textColor: "text-yellow-400",
    rarity: "SR",
  },
  {
    id: "card_scooter_god",
    title: "精算超商貼紙狂熱者",
    description: "傍晚五點準時站在超商冷藏櫃前，用銳利如鷹的雙眼鎖定『65折貼紙』。身手矯健，不屑與原價凡人為伍。",
    imagePrompt: "a small convenience store discount sticker stylized as a cybernetic war medal, high-tech neon green",
    bgColor: "bg-green-950/40 border-green-500",
    textColor: "text-green-400",
    rarity: "R",
  },
  {
    id: "card_add_to_cart",
    title: "購物車虛無收藏家",
    description: "把 99+ 件商品丟進購物車，享受那兩秒鐘的支配感，然後默默關掉 App。省錢大師的無實物精神勝利法。",
    imagePrompt: "a virtual shopping cart glowing with glitch effects, digital neon purple",
    bgColor: "bg-purple-950/40 border-purple-500",
    textColor: "text-purple-400",
    rarity: "R",
  },
  {
    id: "card_blindbox_victim",
    title: "高級塑膠收割者",
    description: "以為自己在收集當代潮流藝術，事實上你只是每個月在幫工廠生產的 30 塊塑膠公仔繳套房租金。",
    imagePrompt: "a cute tiny cartoon skull inside a shiny plastic mystery box, neon pink glowing background",
    bgColor: "bg-pink-950/40 border-pink-500",
    textColor: "text-pink-400",
    rarity: "N",
  },
  {
    id: "card_wallet_ghost",
    title: "錢包真空防禦盾",
    description: "你的錢包太乾淨了，乾淨到連竊盜集團打開都會流下同情的眼淚，並偷偷在裡面塞兩百塊錢。",
    imagePrompt: "ghost floating out of an empty dark leather wallet, spooky but funny blue glow",
    bgColor: "bg-sky-950/40 border-sky-500",
    textColor: "text-sky-400",
    rarity: "N",
  },
];

export const INITIAL_TASKS: MicroTask[] = [
  {
    id: "task_survey_slang",
    title: "填寫 Gen Z 消費焦慮調查問卷",
    sponsor: "BratMetrics 商業分析",
    rewardType: "willpower",
    rewardAmount: 35,
    description: "填寫 5 題關於『為什麼你一邊喊沒錢一邊又點了雙倍大薯』的靈魂拷問，直接獲取盲盒能量！",
    completed: false,
    actionLabel: "開始靈魂對談",
  },
  {
    id: "task_sell_old",
    title: "二手衣物回收上架挑戰",
    sponsor: "兜售虛榮二手平台",
    rewardType: "cash",
    rewardAmount: 150,
    description: "將衣櫃裡那件『買來只穿過一次拍照就打入冷宮』的衣服拍照上架，直接回血變現 150 模擬金！",
    completed: false,
    actionLabel: "拍照上架回血",
  },
  {
    id: "task_ad_roast",
    title: "觀看無情商業洗腦短片",
    sponsor: "多巴胺投射廣告",
    rewardType: "willpower",
    rewardAmount: 20,
    description: "觀看一段長度 15 秒的奢侈品廣告，藉此鍛煉你的『心如止水』抗干擾能力。",
    completed: false,
    actionLabel: "接受洗腦考驗",
  },
  {
    id: "task_pocket_apply",
    title: "申請極簡低保：分享毒舌金句",
    sponsor: "社恐互助協會",
    rewardType: "cash",
    rewardAmount: 50,
    description: "將 AI 給你的無情毒舌戰報分享到社群平台（模擬），回報即送 50 模擬月底低保金！",
    completed: false,
    actionLabel: "分享金句回血",
  },
];
